### ISSUE TITLE
mbtiles can't be merged

### ISSUE THREAD

**Issue by Haves1001** [lambdajack/sequentially-generate-planet-mbtiles#4]
In the final step of the process (when the mbtiles are being merged) the program tries to use a docker container that doesn't exist locally not on docker hub:

```
Unable to find image 'sequential-tippecanoe:latest' locally
docker: Error response from daemon: pull access denied for sequential-tippecanoe, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

I didn't remove any build docker container locally though.

**Comment by Haves1001** [comment]
Mh this might have been caused by me interrupting the initial build of the container when I realised that I needed to free up more disk space.
I'm wondering how the information that the container has been build is persisted?

**Comment by lambdajack** [comment]
Hi again,

Sequentially-generate-planet-mbtiles uses your local docker installation to manage all necessary persistence for it. It will basically ask docker to run a docker container associated with the tag that sequentially-generate-planet-mbtiles previously built.

Sequentially-generate-planet-mbtiles will try to build the relevant container every time it is run. If docker itself reports that the file is built then it simply moves on to the next thing.

that the container is already successfully built, 
I have just run this to check and it worked as expected.

I would try deleting the container using docker directly and starting again.

What OS are you using? are you running with correct permissions (sudo may be needed etc).

**Comment by lambdajack** [comment]
P.s. I am currently working on adding the dependencies as sub-modules for version safety. (though that does not appear to the problem here).

**Comment by Haves1001** [comment]
This is indeed quite weird. It worked well when I manually build the docker container (without deleting any containers) and executed the mbtiles merge afterwards.

I think this might be caused by me interrupting the initial build of the container. Weird though that the next run didn't rebuild the image. 
We can close this though, I think this is a weird corner case. Thank you for your quick response :)
